### ISSUE TITLE
Potions crash the game

### ISSUE THREAD

**Issue by thaKnza** [OreCruncher/MobEffects#4]
*Having a potion splashed on you crashes the game
*Holding a potion crashes the game
*Switching to a potion on your hot bar crashes the game

Several players on my server, myself included, had all of these things happen to them. I was personally stuck in a crash loop because I was holding a potion. Uninstalling MobEffects is the only thing that would stop the crashes until I could log in and switch what I was holding.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 3/3/20 12:08 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at org.orecruncher.mobeffects.effects.PlayerToolbarEffect$HandTracker.update(PlayerToolbarEffect.java:76) ~[?:1.14.4-0.1.0.0] {re:classloading}
	at org.orecruncher.mobeffects.effects.PlayerToolbarEffect$MainHandTracker.update(PlayerToolbarEffect.java:101) ~[?:1.14.4-0.1.0.0] {re:classloading}
	at org.orecruncher.mobeffects.effects.PlayerToolbarEffect.update(PlayerToolbarEffect.java:123) ~[?:1.14.4-0.1.0.0] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.lib.effects.EntityEffectManager.update(EntityEffectManager.java:79) ~[?:1.14.4-0.1.0.0] {re:classloading,pl:runtimedistcleaner:A}
	at org.orecruncher.lib.effects.EntityEffectHandler.lambda$onLivingUpdate$0(EntityEffectHandler.java:100) ~[?:1.14.4-0.1.0.0] {re:classloading}
	at org.orecruncher.lib.effects.EntityEffectHandler$$Lambda$6019/1742398764.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?] {re:classloading}
	at org.orecruncher.lib.effects.EntityEffectHandler.onLivingUpdate(EntityEffectHandler.java:91) ~[?:1.14.4-0.1.0.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_358_EntityEffectHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:312) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:1963) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70071_h_(ClientPlayerEntity.java:173) ~[?:?] {re:classloading,xf:fml:randompatches:RandomPatches ClientPlayerEntity Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:220) ~[?:?] {re:classloading,xf:OptiFine:default,xf:fml:sndctrl:sndctrl_clientworld_transformer}
	at net.minecraft.client.world.ClientWorld$$Lambda$6017/1549180590.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:179) ~[?:?] {re:classloading,xf:OptiFine:default,xf:fml:sndctrl:sndctrl_clientworld_transformer}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1344) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:869) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.0.jar:28.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$421/420502151.call(Unknown Source) [forge-1.14.4-28.2.0.jar:28.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.orecruncher.mobeffects.effects.PlayerToolbarEffect$HandTracker.update(PlayerToolbarEffect.java:76)
	at org.orecruncher.mobeffects.effects.PlayerToolbarEffect$MainHandTracker.update(PlayerToolbarEffect.java:101)
	at org.orecruncher.mobeffects.effects.PlayerToolbarEffect.update(PlayerToolbarEffect.java:123)
	at org.orecruncher.lib.effects.EntityEffectManager.update(EntityEffectManager.java:79)
	at org.orecruncher.lib.effects.EntityEffectHandler.lambda$onLivingUpdate$0(EntityEffectHandler.java:100)
	at org.orecruncher.lib.effects.EntityEffectHandler$$Lambda$6019/1742398764.accept(Unknown Source)
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161)
	at org.orecruncher.lib.effects.EntityEffectHandler.onLivingUpdate(EntityEffectHandler.java:91)
	at net.minecraftforge.eventbus.ASMEventHandler_358_EntityEffectHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:312)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:1963)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:232)
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70071_h_(ClientPlayerEntity.java:173)
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:220)
	at net.minecraft.client.world.ClientWorld$$Lambda$6017/1549180590.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.client.entity.player.ClientPlayerEntity)
	Entity ID: 5843
	Entity Name: Knots
	Entity's Exact location: -240.35, 98.00, 1333.97
	Entity's Block location: World: (-241,98,1333), Chunk: (at 15,6,5 in -16,83; contains blocks -256,0,1328 to -241,255,1343), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:684)
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:179)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Knots'/5843, l='MpServer', x=-240.35, y=98.00, z=1333.97]]
	Chunk stats: Client Chunk Cache: 3025, 2398
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-205,64,284), Chunk: (at 3,4,12 in -13,17; contains blocks -208,0,272 to -193,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 40217707 game time, 26548417 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:574)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$421/420502151.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1706789728 bytes (1627 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_F5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.0
	FML Language Providers: 
		javafml@28.2
		minecraft@1
		kotlinfml@1.4.0
	Mod List: 
		tetra-1.14.4-1.20.1.jar Tetra {tetra@1.14.4-1.20.1 DONE}
		inventorysorter-1.14.4-16.2.0.jar Simple Inventory Sorter {inventorysorter@16.2.0 DONE}
		SoundControl-1.14.4-0.1.0.0.jar §3Dynamic Surroundings: §eSound Control {sndctrl@1.14.4-0.1.0.0 DONE}
		curiousshulkerboxes-FORGE-1.14.4-1.0.0.2.jar Curious Shulker Boxes {curiousshulkerboxes@FORGE-1.14.4-1.0.0.2 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		AttributeFix-1.14.4-3.0.2.jar AttributeFix {attributefix@3.0.2 DONE}
		cosmeticbeds-FORGE-1.14.4-2.0.0.1.jar Cosmetic Beds {cosmeticbeds@FORGE-1.14.4-2.0.0.1 DONE}
		nether+-1.4.0-1.14.4.jar betternether {betternether@1.0.0 DONE}
		Upgrade-Aquatic-1.14.4-v1.4.10.jar Upgrade Aquatic {upgrade_aquatic@1.4.9 DONE}
		KleeSlabs_1.14.4-7.4.8.jar KleeSlabs {kleeslabs@7.4.8 DONE}
		buildbasics-1.1.0.jar Builder's Basics {buildbasics@1.1.0 DONE}
		invtweaks-1.14.4-1.0.1.jar Inventory Tweaks Reborn {invtweaks@1.14.4-1.0.1 DONE}
		ensorcellation-1.14.4-0.2.0b.jar Ensorcellation {ensorcellation@0.2.0b DONE}
		Waystones_1.14.4-5.1.1_KN.jar Waystones {waystones@5.1.1 DONE}
		ForgeEndertech-1.14.4-5.2.1.0-build.0076.jar Forge Endertech {forgeendertech@5.2.1.0 DONE}
		mgui-1.14.4-1.2.0.jar mgui {mgui@1.2.0 DONE}
		Controlling-5.0.6.jar Controlling {controlling@5.0.6 DONE}
		SereneSeasons-1.14.4-2.0.0.40-universal.jar Serene Seasons {sereneseasons@1.14.4-2.0.0.40 DONE}
		decorative_blocks_5.jar Decorative Blocks {decorative_blocks@1.5 DONE}
		PyramidPlunder-1.14.4-1.1.jar Pyramid Plunder {pyramidplunder@1.14.4-1.0 DONE}
		DungeonCrawl-1.14.4-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		cofh_core-1.14.4-0.2.0b.jar CoFH Core {cofh_core@0.2.0b DONE}
		The-Endergetic-Expansion-1.14.4-v1.1.2.jar The Endergetic Expansion {endergetic@1.1.2 DONE}
		guardvillagers-1.14.4-1.0.1.jar Guard Villagers {guardvillagers@1.0.1 DONE}
		randompatches-1.14.4-1.21.0.0.jar RandomPatches {randompatches@1.14.4-1.21.0.0 DONE}
		Waddles-1.14.4-0.8.3.jar Waddles {waddles@1.14.4-0.8.3 DONE}
		ProgressiveBosses-2.1.4.jar Progressive Bosses {progressivebosses@2.1.4 DONE}
		Morpheus-1.14.4-4.2.44.jar Morpheus {morpheus@version DONE}
		environmentalcreepers-forge-1.14.4-1.6.0.jar Environmental Creepers {environmentalcreepers@1.6.0 DONE}
		SnowRealMagic-1.14.4-1.7.1.jar Snow! Real Magic! {snowrealmagic@1.7.1 DONE}
		Kiwi-1.14.4-2.6.3.jar Kiwi {kiwi@2.6.3 DONE}
		carpetstairsmod-mc1.14-v1.3.jar Carpet Stairs Mod {carpetstairsmod@1.1 DONE}
		horsestandstill-1.14.4-0.0.1.jar  {horsestandstill@1.14.4-0.0.1 DONE}
		CraftTweaker-1.14.4-5.0.1.133.jar CraftTweaker {crafttweaker@5.0.1.133 DONE}
		campfiretorches-1.14.4-1.0.3.jar Campfire Torches {campfiretorches@1.14.4-1.0.3 DONE}
		forge-1.14.4-28.2.0-universal.jar Forge {forge@28.2.0 DONE}
		Bones-1.14.4-1.3.2.jar Bones {bones@1.14.4-1.3.2 DONE}
		NoIncreasingRepairCost-1.0.jar No Increasing Repair Cost {noincreasingrepaircost@NONE DONE}
		nmdar_1.14-3.8.jar Named Areas {nmdar@3.8 DONE}
		dcintegration-1.1.5-1.14.jar Discord Integration {dcintegration@1.1.5 DONE}
		discholder-1.1a.jar Disc Holder {discholder@1.1a DONE}
		infernalmobs-1.14.4.6.jar Infernal Mobs {infernalmobs@1.14.4.6 DONE}
		CraftingTweaks_1.14.4-10.2.1.jar Crafting Tweaks {craftingtweaks@10.2.1 DONE}
		forge-1.14.4-28.2.0-client.jar Minecraft {minecraft@1.14.4 DONE}
		mcw-bridges-1.0.3-mc1.14.4.jar Macaw's Bridges {mcwbridges@1.0.3 DONE}
		logprot-1.14.4-1.1.jar Logprot {logprot@1.1 DONE}
		itlt-1.14.4-1.0.2.jar It's the little things {itlt@1.14.4-1.0.2 DONE}
		EnchantmentDescriptions-1.14.4-1.3.9.jar EnchantmentDescriptions {enchdesc@1.3.9 DONE}
		AmbientSounds_v3.0.16_mc1.14.4.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		BiomesOPlenty-1.14.4-9.0.0.262-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.259 DONE}
		guardillagers-1.14.4-1.0.1.jar GuardIllagers {guardillagers@1.0.1 DONE}
		fairylights-2.1.15-1.14.4.jar Fairy Lights {fairylights@2.1.15 DONE}
		MobEffects-1.14.4-0.1.0.0.jar §3Dynamic Surroundings: §eMob Effects {mobeffects@1.14.4-0.1.0.0 DONE}
		curios-FORGE-1.14.4-1.0.6.1.jar Curios API {curios@FORGE-1.14.4-1.0.6.1 DONE}
		corail_woodcutter-1.1.1-1.14.4.jar Corail Woodcutter {corail_woodcutter@1.1.1 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		camera-1.4.10.jar Camera Mod {camera@1.4.10 DONE}
		placeableitems-4.0.0.jar Placeable Items {placeableitems@4.0 DONE}
		betteranimals-1.14.4-5.3.0.jar Cyber's Better Animal Models {betteranimals@5.3.0 DONE}
		libnonymous-1.14.4-1.0.4.25.jar Libnonymous {libnonymous@1.0.4.25 DONE}
		RiddleChests-1.0.2.3.jar Riddle Chests {riddlechests@1.0.2.3 DONE}
		Harvest-forge-1.14.4-1.2.10-23.jar Harvest {harvest@version DONE}
		tubesreloaded-1.14.4-1.1.1c.jar Tubes Reloaded {tubesreloaded@1.14.4-1.1.1c DONE}
		EnigmaticLegacy-1.6.4.jar Enigmatic Legacy {enigmaticlegacy@1.6.4 DONE}
		AmbientEnvironment-2.0.1.jar Ambient Environment {ambientenvironment@2.0.1 DONE}
		hidden-levers.jar Hidden Levers {hiddenlevers@1.0 DONE}
		furniture-7.0.0-pre15-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre15 DONE}
		AppleSkin-mc1.14.4-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		nps_1.14-2.1.jar Nether Portal Spread {nps@2.1 DONE}
		AdChimneys-1.14.4-4.0.0.1-build.0072.jar Advanced Chimneys {adchimneys@4.0.0.1 DONE}
		tramplestopper-1.14.4-2.0.0.26-universal.jar Trample Stopper {tramplestopper@1.14.4-2.0.0.26-universal DONE}
		Charm-1.14.4-1.4.3.jar Charm {charm@1.14.4-1.4.3 DONE}
		Quark-r2.0-212.jar Quark {quark@r2.0-212 DONE}
		bwncr-1.14.4-3.5.12.jar Bad Wither No Cookie Reloaded {bwncr@1.14.4-3.5.12 DONE}
		horsestats-1.14.4-1.0.1.jar Horse Stats {horsestats@1.0.1 DONE}
		BetterAdvancements-1.14.4-0.1.0.94.jar Better Advancements {betteradvancements@0.1.0.94 DONE}
	Kiwi Modules: 
		kiwi:contributors
		snowrealmagic:snowrealmagic
	Launched Version: 1.14.4-forge-28.2.0
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.66, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources, vanilla, file/Vanilla-PBR-1-0-1.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
	OptiFine Version: OptiFine_1.14.4_HD_U_F5
	OptiFine Build: 20191204-141250
	Render Distance Chunks: 28
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.262 Extreme-VL.zip
	OpenGlVersion: 4.6.0 NVIDIA 441.66
	OpenGlRenderer: GeForce GTX 1080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by OreCruncher** [comment]
This happen with Vanilla potions, or are you using modded potions?  I can't dupe in my dev environment with vanilla potions, but I think I know what the problem is.

**Comment by thaKnza** [comment]
It was any potion. We tested most of em including vanilla potions like slowfall and healing.

**Comment by OreCruncher** [comment]
Mods in your pack?  What it looks like is that potions/items were registered after the expected registration phase during startup.

**Comment by thaKnza** [comment]
The list of mods is at the end of the crash report. I'm not sure which mods alter potions, possibly Quark or Charm.
